// The one channel to the core: `confyg-ffi`'s two exports, `dispatch` and `check`.
// `wasm-pack build crates/confyg-ffi --target web` writes the glue to
// `crates/confyg-ffi/pkg/`, which is a build artifact, so the module is loaded through a
// non-literal specifier — the renderer typechecks whether or not the WASM has been built.
import type { Path, SetterSnapshot, Violation } from "./types.js";

// A static import cannot work here: the glue is generated by `wasm-pack`, so it does not
// exist in a fresh checkout and would fail typecheck and build before the WASM is built.
const GLUE = "../../crates/confyg-ffi/pkg/confyg_ffi.js";

interface Glue {
  default: (input?: unknown) => Promise<unknown>;
  Handle: new () => object;
  dispatch: (handle: object, requestJson: string) => string;
  check: (handle: object, pathJson: string, literal: string) => string;
}

export class Boundary {
  private constructor(
    private readonly glue: Glue,
    private readonly handle: object,
  ) {}

  static async load(): Promise<Boundary> {
    const glue = (await import(/* @vite-ignore */ GLUE)) as Glue;
    await glue.default();
    return new Boundary(glue, new glue.Handle());
  }

  /** A `Request` in, a `SetterSnapshot` out. A malformed request comes back in the envelope. */
  dispatch(request: unknown): SetterSnapshot {
    return JSON.parse(this.glue.dispatch(this.handle, JSON.stringify(request)));
  }

  /**
   * The validator's own Violations for a buffer that is not yet committed. Live checks
   * cross the boundary rather than being reimplemented here, so a form warning and a
   * Violation can never disagree (design §7).
   */
  check(path: Path, literal: string): Violation[] {
    return JSON.parse(this.glue.check(this.handle, JSON.stringify(path), literal));
  }
}
